import {
  faInstagram,
  faLinkedin,
  faFacebook,
  faTwitter,
  faYoutube,
  faTiktok,
} from "@fortawesome/free-brands-svg-icons";

export const reviewsData = [
  {
    img: "/assets/img1.jpg",
    text: "This product is amazing! It has changed my life for the better.",
    name: "John Doe",
  },
  {
    img: "/assets/img2.jpg",
    text: "I highly recommend this service. Excellent quality and fast delivery!",
    name: "Jane Smith",
  },
  {
    img: "/assets/img3.jpg",
    text: "Best purchase I've made in a long time. Great value for the price.",
    name: "Sarah Brown",
  },
];

export const footerSections = {
  integrations: [
    "Shopify",
    "Etsy",
    "eBay",
    "Amazon",
    "TikTok Shop",
    "PrestaShop",
    "BigCommerce",
    "Wix",
    "WooCommerce",
    "Squarespace",
    "Printify API",
    "Printify Pop-Up Store",
    "Shutterstock",
  ],
  discover: [
    "Blog",
    "Guides",
    "Products",
    "Etsy print-on-demand",
    "Shopify print-on-demand",
    "Woocommerce print-on-demand",
    "Wix print-on-demand",
    "Squarespace print-on-demand",
    "Make Your Own Shirt",
    "Brands",
    "Pricing",
    "Shipping Rates",
    "Mockup Generator",
  ],
  startSelling: [
    "Custom T-shirts",
    "Custom Hoodies",
    "Custom Mugs",
    "Custom Socks",
    "Custom Backpacks",
    "Custom Branding",
    "Sell on Etsy",
    "Sell on Social Media",
    "Free T-shirt Designs",
    "Custom Products",
    "Custom All-Over-Print Hoodies",
    "Start a Clothing Line",
    "Start POD Business",
    "Bulk Orders",
    "Transferring To Printify",
  ],
  printify: [
    "Print on Demand",
    "Print Providers",
    "Experts Program",
    "Printify Express Delivery",
    "Become a Partner",
    "About",
    "Printify Quality Promise",
    "Jobs",
    "Webinars",
    "Printing Profits Podcast",
    "Contact Us",
    "Affiliate",
    "Contact Sales",
    "POD Glossary",
    "Network Fulfillment Status",
    "Merchant Protection",
    "Security",
  ],
};

export const socialIcons = [
  { icon: faLinkedin, label: "LinkedIn" },
  { icon: faInstagram, label: "Instagram" },
  { icon: faFacebook, label: "Facebook" },
  { icon: faTwitter, label: "Twitter" },
  { icon: faYoutube, label: "YouTube" },
  { icon: faTiktok, label: "TikTok" },
];
